# kp exception

<!-- !! processed by numpydoc !! -->

---
 
### **exception** kp.ApiKPException(api_return_code, function_name, result=None)
This class represents an Exception thrown when a KneronPLUS API returns error code.

<!-- !! processed by numpydoc !! -->

#### with_traceback()
Exception.with_traceback(tb) â€“
set self.__traceback__ to tb and return self.

<!-- !! processed by numpydoc !! -->
